### ISSUE TITLE
The style is applied if github appears anywhere in the url

### ISSUE THREAD

**Issue by deadeyejoe** [DarkThemeHub/GithubDarkTheme#134] opened 2020-01-16 12:32 UTC
**Describe the bug**
Or at least that appears to be the case. I'm not great with interpreting regexes!

Sepcifically I'm editing a lambda and the url is https://eu-west-1.console.aws.amazon.com/lambda/home?region=eu-west-1#/functions/github-pull-request-notification?tab=configuration. The style is applied to some elements on the page and it makes them unreadable.

**Expected behavior**
The style should not apply to this url.

**Screenshots**
![image](https://user-images.githubusercontent.com/10846066/72525352-d716da80-385b-11ea-81b6-69981c37fcd9.png)

**Comment by acoop133** [comment] 2020-01-16 15:56
This is a duplicate of #120

see https://github.com/DarkThemeHub/GithubDarkTheme/issues/120#issuecomment-573468471

The new regex does cover this, however i found that stylus' regex matcher is a bit shitty. 
If you're not on the latest theme version, should update :)
[Install/update instructions](https://github.com/DarkThemeHub/GithubDarkTheme#option-1-recommended-due-to-privacy-concerns-with-userstylesorg)

[Paste your regex in here to test against new regex](https://regex101.com/r/bW6cYw/3)

**Closed** 2020-01-16 15:59 UTC
Labels: duplicate

**Comment by acoop133** [comment] 2020-01-16 16:03
So it might be the case that stylus fixed their regex comparer and our new regex works now. So yeah, im assuming you're not on the latest theme version

**Comment by deadeyejoe** [comment] 2020-01-20 10:50
Ok great, thanks for getting back to me and sorry for the duplicate

**Comment by Snazzie** [comment] 2020-01-20 11:01
No problem, did you manage to sort it out?

**Comment by deadeyejoe** [comment] 2020-01-20 11:26
Yup. Updating manually did the trick.

**Comment by Snazzie** [comment] 2020-01-20 11:31
Yeah, you have to manually update each time which is annoying. 
Thats why this exists :P i just need to get it approved by the chrome store 
https://github.com/DarkThemeHub/GithubDarkTheme/pull/129
