### ISSUE TITLE
The style is applied to non-github websites containing the word github in the URL

### ISSUE THREAD

**Issue by jasonwynn10** [DarkThemeHub/GithubDarkTheme#167] opened 2020-06-05 22:05 UTC
**Describe the bug**
The style is applied to non-github websites containing the word `github` in the URL

**Expected behavior**
Non-github websites should not be affected by the style.

**Screenshots**
![image](https://user-images.githubusercontent.com/16521025/83926123-f5bc3600-a756-11ea-953e-513dc45c374b.png)
![image](https://user-images.githubusercontent.com/16521025/83926143-066cac00-a757-11ea-8bef-9ddb37d31a86.png)

**Comment by Snazzie** [comment] 2020-06-05 22:07
Please install the theme according to the steps given here https://github.com/DarkThemeHub/GithubDarkTheme#install-the-theme

**Comment by Snazzie** [comment] 2020-06-05 22:08
duplicate of https://github.com/DarkThemeHub/GithubDarkTheme/issues/153

**Closed** 2020-06-05 22:07 UTC
Labels: duplicate

**Comment by Snazzie** [comment] 2020-06-05 22:13
Also make sure that you remove the theme installed via stylus website.
